# Generated by Django 5.2.7 on 2025-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rate',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
