# Generated by Django 5.2.7 on 2025-10-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_game_rate_delete_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
